//RECIPE
export const GET_CURRENT_RECIPE_START = "GET_CURRENT_RECIPE_START";
export const GET_CURRENT_RECIPE_SUCCESS = "GET_CURRENT_RECIPE_SUCCESS";
export const GET_CURRENT_RECIPE_ERROR = "GET_CURRENT_RECIPE_ERROR";
export const FILTER_CURRENT_RECIPES = "FILTER_CURRENT_RECIPES";

export const CHANGE_RECIPE_SEARCH = "CHANGE_RECIPE_SEARCH";
export const GET_CHANGE_NUMBER = "GET_CHANGE_NUMBER";
export const CHANGE_PAGE = "CHANGE_PAGE";